spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: library

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.changelogs
logging:
  level:
    root: ERROR

