DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS(AUTHOR_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, AUTHOR_NAME VARCHAR(255) NOT NULL UNIQUE);
CREATE TABLE GENRES(GENRE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, GENRE_NAME VARCHAR(255) NOT NULL UNIQUE);
CREATE TABLE BOOKS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), AUTHOR BIGINT,
FOREIGN KEY (AUTHOR) REFERENCES AUTHORS (AUTHOR_ID), GENRE BIGINT, FOREIGN KEY (GENRE) REFERENCES GENRES (GENRE_ID));
CREATE TABLE COMMENTS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, COMMENT VARCHAR(255), BOOK BIGINT, FOREIGN KEY (BOOK)
REFERENCES BOOKS(ID) on delete cascade, USER_NAME VARCHAR(255));
CREATE TABLE USERS(USER_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, LOGIN VARCHAR(255) NOT NULL UNIQUE,
PASSWORD VARCHAR(255) NOT NULL, ROLE VARCHAR(255) NOT NULL, IS_ACCOUNT_NON_EXPIRED BOOLEAN NOT NULL,
IS_ACCOUNT_NON_LOCKED BOOLEAN NOT NULL, IS_CREDENTIALS_NON_EXPIRED BOOLEAN NOT NULL, IS_ENABLED BOOLEAN NOT NULL);