DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS(AUTHOR_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, AUTHOR_NAME VARCHAR(255) NOT NULL UNIQUE);
CREATE TABLE GENRES(GENRE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, GENRE_NAME VARCHAR(255) NOT NULL UNIQUE);
CREATE TABLE BOOKS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), AUTHOR BIGINT,
FOREIGN KEY (AUTHOR) REFERENCES AUTHORS (AUTHOR_ID), GENRE BIGINT, FOREIGN KEY (GENRE) REFERENCES GENRES (GENRE_ID));