DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS(AUTHOR_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, AUTHOR_NAME VARCHAR(255));
CREATE TABLE GENRES(GENRE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, GENRE_NAME VARCHAR(255));
CREATE TABLE BOOKS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), AUTHOR VARCHAR(255),
FOREIGN KEY (AUTHOR) REFERENCES AUTHORS (AUTHOR_NAME), GENRE VARCHAR(255), FOREIGN KEY (GENRE) REFERENCES GENRES (GENRE_NAME));